### ISSUE TITLE
Spark support

### ISSUE THREAD

**Issue by xiaohan2012** [paulgb/runipy#128]
How to run notebooks with Spark jobs in it?

**Comment by krautt** [comment]
maybe more specifically, how to run pyspark jobs with the   PYSPARK_DRIVER_PYTHON_OPTS="notebook" flag set.

**Comment by jakirkham** [comment]
Not sure. I don't really use Spark/PySpark. How do you run these normally with the notebook?

**Comment by maurodoglio** [comment]
Starting it [this way](https://github.com/mozilla/emr-bootstrap-spark/blob/master/ansible/files/telemetry.sh#L159) seems to be the most standard way to do it. We used to use ipython profiles in the past but that stopped working with Spark 2.0. [Here](https://github.com/mozilla/emr-bootstrap-spark/blob/3c4624f759ccaea0c33a2e1ee6f70fa5b3cf1714/ansible/files/telemetry.sh#L127-L129) is what we used to do.

**Comment by krautt** [comment]
Thanks! that did indeed work.  this is great.

**Comment by krautt** [comment]
FWIW,  I found the easiest way to run a notebook in spark is to use jupyter nbconvert to convert it to a .py and run that as an argument to spark-submit.  you can wrap it and delete the .py afterward if you want to clean up.  Otherwise you can't seem to pass Spark the args needed to get it to run on a yarn cluster.
