### ISSUE TITLE
Import user args from a config file

### ISSUE THREAD

**Issue by summerela** [paulgb/runipy#68]
Hi-

This is great! Is it possible to pass arguments from a config file instead of from the command line? I've been toying around with it and can't quite figure it out. 

Thanks!

**Comment by jakirkham** [comment]
How do you mean pass arguments via a config file instead of the command line? Are you referring to environment variables?

If so, I think the best course of action would be to have a cell in the notebook that reads a config file of your chosen format. You could add some default values in the same cell suppose a config file is not found, if you wish.

**Comment by summerela** [comment]
Sounds like exactly what I need to do. Thank you!

On Wed, Sep 23, 2015 at 6:43 AM, jakirkham <notifications@github.com> wrote:

> How do you mean pass arguments via a config file instead of the command
> line? Are you referring to environment variables?
>
> If so, I think the best course of action would be to have a cell in the
> notebook that reads a config file of your chosen format. You could add some
> default values in the same cell suppose a config file is not found, if you
> wish.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulgb/runipy/issues/68#issuecomment-142605422>.
>



-- 
Thanks,
Summer Rae
summerrae78@gmail.com

**Comment by jakirkham** [comment]
Thanks for you interest in `runipy`. I am going to go ahead and close this issue.

If you have any other questions, feel free to put them here if they are related and I'll reopen if you are unable or put them in a new issue if unrelated.
